# Generated by Django 2.2 on 2020-07-09 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UWorksmain',
            fields=[
                ('pk_works_main', models.AutoField(help_text='项目id', primary_key=True, serialize=False, verbose_name='项目id')),
                ('name', models.CharField(help_text='全景项目名称', max_length=30, verbose_name='全景项目名称')),
                ('profile', models.TextField(blank=True, help_text='场景简介', null=True, verbose_name='场景简介')),
                ('thumb_path', models.CharField(default='', help_text='略缩图', max_length=255, verbose_name='略缩图')),
                ('view_uuid', models.CharField(default='', help_text='图纸编码', max_length=16, verbose_name='图纸编码')),
                ('photo_date', models.DateTimeField(default=datetime.datetime.now, help_text='拍摄时间', verbose_name='拍摄时间')),
                ('privacy_flag', models.IntegerField(default=True, help_text='允许公开浏览', verbose_name='允许公开浏览')),
                ('privacy_password', models.CharField(blank=True, help_text='私有密码', max_length=32, null=True, verbose_name='私有密码')),
                ('cdn_host', models.CharField(default='baidu.com', help_text='cdn服务器域名', max_length=100, verbose_name='cdn服务器域名')),
                ('hidelogo_flag', models.IntegerField(default=True, help_text='logo隐藏', verbose_name='logo隐藏')),
                ('hideuser_flag', models.IntegerField(default=True, help_text='作者隐藏', verbose_name='作者隐藏')),
                ('flag_publish', models.IntegerField(default=True, help_text='是否发布作品', verbose_name='是否发布作品')),
                ('browsing_num', models.IntegerField(default=True, help_text='浏览量', verbose_name='浏览量')),
                ('praised_num', models.IntegerField(default=100, help_text='点赞量', verbose_name='点赞量')),
                ('hideshare_flag', models.IntegerField(default=True, help_text='隐藏分享', verbose_name='隐藏分享')),
                ('hidevrglasses_flag', models.IntegerField(default=True, help_text='隐藏vr眼镜', verbose_name='隐藏vr眼镜')),
                ('hideviewnum_flag', models.PositiveIntegerField(default=True, help_text='隐藏人气', verbose_name='隐藏人气')),
                ('sort', models.SmallIntegerField(default=999, help_text='管理员定义的排序', verbose_name='管理员定义的排序')),
                ('user_sort', models.SmallIntegerField(default=999, help_text='用户自定义显示排序', verbose_name='用户自定义显示排序')),
                ('hideprofile_flag', models.IntegerField(default=True, help_text='是否显示简介', verbose_name='是否显示简介')),
                ('hidepraise_flag', models.IntegerField(default=True, help_text='是否允许点赞', verbose_name='是否允许点赞')),
                ('flag_allowed_recomm', models.IntegerField(default=True, help_text='是否允许推荐', verbose_name='是否允许推荐')),
                ('recommend', models.IntegerField(default=True, help_text='是否推荐', verbose_name='是否推荐')),
                ('user_recommend', models.IntegerField(default=True, help_text='用户自定义是否允许管理员推荐', verbose_name='用户自定义是否允许管理员推荐')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, help_text='创建时间', verbose_name='创建时间')),
            ],
            options={
                'db_table': 'u_worksmain',
            },
        ),
    ]
